spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: microconfig-test-client5

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:hl@localhost:7301/eureka
  register-with-eureka: false

info:
  app.name: microcloud-config-client-dev2
  company.name: enjoy2
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: microconfig-test-client5

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:hl@localhost:7301/eureka
  register-with-eureka: false
  
info:
  app.name: microcloud-config-client-beta2
  company.name: enjoy
